---
name: "Jellyfin manifest manager"
description: "Update a Jellyfin manifest file in a GitHub repository, and publish to gh-pages."
author: "LizardByte"
inputs:
  committer_email:
    description: "The email address of the committer to the gh-pages branch."
    required: true
  committer_name:
    description: "The name of the committer to the gh-pages branch."
    required: true
  branch:
    description: "The branch where gh-pages is hosted."
    default: "gh-pages"
    required: false
  gh_pages_url:
    description: "The URL where the gh-pages branch is hosted."
    default: "https://lizardbyte.github.io/jellyfin-plugin-repo"
    required: false
  github_token:
    description: "The GitHub token used to push to the gh-pages branch."
    required: true
  release_tag:
    description: "The tag name of the release."
    default: "latest"
    required: false
  repository:
    description: "The repository where gh-pages is hosted."
    default: "LizardByte/jellyfin-plugin-repo"
    required: false
  plugin_url:
    description: "The URL where the plugin zip file is (or will be) hosted. This will be evaluated if empty"
    default: ""
    required: false
  zipfile:
    description: "The path to the plugin zip file. This will be evaluated if empty"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup inputs
      id: inputs
      shell: bash
      run: |
        branch=${{ inputs.branch }}
        gh_pages_url=${{ inputs.gh_pages_url }}
        repository=${{ inputs.repository }}
        release_tag=${{ inputs.release_tag }}

        # the repository running this action
        source_repository=${{ github.event.repository.name }}

        if [ -z "${{ inputs.zipfile }}" ]; then
          # repository name in lowercase
          repository_name=$(echo ${source_repository} | tr '[:upper:]' '[:lower:]')
          zipfile_name=${repository_name}.zip
          zipfile_path=${{ github.workspace }}/${repository_name}.zip
        else
          zipfile_name=$(basename ${{ inputs.zipfile }})
          zipfile_path=${{ inputs.zipfile }}
        fi

        if [ -z "${{ inputs.plugin-url }}" ]; then
          plugin_url=${{ github.event.repository.html_url }}/releases/download/${release_tag}/${zipfile_name}
        else
          plugin_url=${{ inputs.plugin_url }}
        fi

        echo "branch=${branch}" >> $GITHUB_OUTPUT
        echo "gh_pages_url=${gh_pages_url}" >> $GITHUB_OUTPUT
        echo "repository=${repository}" >> $GITHUB_OUTPUT
        echo "release_tag=${release_tag}" >> $GITHUB_OUTPUT

        echo "source_repository=${source_repository}" >> $GITHUB_OUTPUT

        echo "plugin_url=${plugin_url}" >> $GITHUB_OUTPUT
        echo "zipfile_name=${zipfile_name}" >> $GITHUB_OUTPUT
        echo "zipfile_path=${zipfile_path}" >> $GITHUB_OUTPUT

    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        update-environment: false

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        ${{ steps.setup-python.outputs.python-path }} -m pip install --upgrade pip setuptools wheel
        ${{ steps.setup-python.outputs.python-path }} -m pip install -r requirements.txt

    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.inputs.outputs.branch }}
        repository: ${{ steps.inputs.outputs.repository }}
        path: ${{ steps.inputs.outputs.branch }}
        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of the personal token
        fetch-depth: 0  # otherwise, will fail to push refs to dest repo

    - name: JPRM repo init/add
      shell: bash
      run: |
        # initialize repo if it doesn't exist
        ${{ steps.setup-python.outputs.python-path }} \
          -m jprm \
          repo init \
          ${{ steps.inputs.outputs.branch }} || true  # ignore error if already exists

        # add plugin to repo
        ${{ steps.setup-python.outputs.python-path }} \
          -m jprm \
          repo add \
          --url ${{ steps.inputs.outputs.gh_pages_url }} \
          --plugin-url ${{ steps.inputs.outputs.plugin_url }} \
          ${{ steps.inputs.outputs.branch }} \
          ${{ steps.inputs.outputs.zipfile_path }}

    - name: Publish gh-pages
      uses: actions-js/push@v1.5
      with:
        github_token: ${{ inputs.github_token }}
        author_email: ${{ inputs.committer_email }}
        author_name: ${{ inputs.committer_name }}
        directory: ${{ steps.inputs.outputs.branch }}
        branch: ${{ steps.inputs.outputs.branch }}
        force: false
        message: "Bump ${{ steps.inputs.outputs.source_repository }} to ${{ steps.inputs.outputs.release_tag }}"
        repository: ${{ steps.inputs.outputs.repository }}
