---
name: "Jellyfin manifest manager"
description: "Update a Jellyfin manifest file in a GitHub repository, and publish to gh-pages."
author: "LizardByte"

branding:
  color: "green"
  icon: "package"

inputs:
  action:
    description: "The jprm action to perform. Choices are `add` or `remove`."
    default: "add"
    required: false
  committer_email:
    description: "The email address of the committer to the gh-pages branch."
    required: true
  committer_name:
    description: "The name of the committer to the gh-pages branch."
    required: true
  branch:
    description: "The branch where gh-pages is hosted."
    default: "gh-pages"
    required: false
  gh_pages_url:
    description: "The URL where the gh-pages branch is hosted."
    default: "https://lizardbyte.github.io/jellyfin-plugin-repo"
    required: false
  github_token:
    description: "The GitHub token used to push to the gh-pages branch."
    required: true
  release_tag:
    description: "The tag name of the release."
    default: "latest"
    required: false
  repository:
    description: "The repository where gh-pages is hosted."
    default: "LizardByte/jellyfin-plugin-repo"
    required: false
  plugin_url:
    description: "The URL where the plugin zip file is (or will be) hosted. This will be evaluated if empty."
    default: ""
    required: false
  zipfile:
    description: "The path to the plugin zip file. This will be evaluated if empty."
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup inputs
      id: inputs
      shell: bash
      env:
        INPUTS_ACTION: ${{ inputs.action }}
        INPUTS_BRANCH: ${{ inputs.branch }}
        INPUTS_GH_PAGES_URL: ${{ inputs.gh_pages_url }}
        INPUTS_PLUGIN_URL: ${{ inputs.plugin_url }}
        INPUTS_REPOSITORY: ${{ inputs.repository }}
        INPUTS_RELEASE_TAG: ${{ inputs.release_tag }}
        INPUTS_ZIPFILE: ${{ inputs.zipfile }}
        SOURCE_REPOSITORY: ${{ github.event.repository }}
        SOURCE_REPOSITORY_NAME: ${{ github.event.repository.name }}  # the repository running this action
        SOURCE_REPOSITORY_URL: ${{ github.event.repository.html_url }}
      run: |
        # switch to ensure the action is valid
        case ${INPUTS_ACTION} in
          add)
            ;;
          remove)
            ;;
          *)
            echo ":error: Invalid action: ${INPUTS_ACTION}"
            echo "Valid actions are 'add' or 'remove'"
            exit 1
            ;;
        esac

        if [[ "${SOURCE_REPOSITORY}" =~ ^LizardByte/ ]]; then
          # strip `-jellyfin` from the end of the name, if in the LizardByte org
          plugin_name=$(echo ${SOURCE_REPOSITORY_NAME}} | sed 's/-jellyfin$//' | tr '[:upper:]' '[:lower:]')
        else
          plugin_name=$(echo ${SOURCE_REPOSITORY_NAME} | tr '[:upper:]' '[:lower:]')
        fi

        # release version, tag without v prefix
        release_version=$(echo ${INPUTS_RELEASE_TAG} | sed 's/^v//')

        if [ -z "${INPUTS_ZIPFILE}" ]; then
          # repository name in lowercase
          repository_name=$(echo ${SOURCE_REPOSITORY_NAME} | tr '[:upper:]' '[:lower:]')
          zipfile_name=${repository_name}.zip
          zipfile_path=${GITHUB_WORKSPACE}/${repository_name}.zip
        else
          zipfile_name=$(basename ${INPUTS_ZIPFILE})
          zipfile_path=${INPUTS_ZIPFILE}
        fi

        if [ -z "${INPUTS_PLUGIN_URL}" ]; then
          plugin_url=${SOURCE_REPOSITORY_URL}/releases/download/${INPUTS_RELEASE_TAG}/${zipfile_name}
        else
          plugin_url=${INPUTS_PLUGIN_URL}
        fi

        {
          echo "action=${INPUTS_ACTION}"
          echo "branch=${INPUTS_BRANCH}"
          echo "gh_pages_url=${INPUTS_GH_PAGES_URL}"
          echo "repository=${INPUTS_REPOSITORY}"
          echo "release_tag=${INPUTS_RELEASE_TAG}"
          echo "release_version=${release_version}"
          echo "source_repository=${SOURCE_REPOSITORY_NAME}"
          echo "plugin_url=${plugin_url}"
          echo "zipfile_name=${zipfile_name}"
          echo "zipfile_path=${zipfile_path}"
        } >> "${GITHUB_OUTPUT}"

    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: "3.14"
        update-environment: false

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        ${{ steps.setup-python.outputs.python-path }} -m pip install --upgrade pip setuptools wheel
        ${{ steps.setup-python.outputs.python-path }} -m pip install -r requirements.txt

    - name: Checkout gh-pages
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        ref: ${{ steps.inputs.outputs.branch }}
        repository: ${{ steps.inputs.outputs.repository }}
        path: ${{ steps.inputs.outputs.branch }}
        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of the personal token
        fetch-depth: 0  # otherwise, will fail to push refs to dest repo

    - name: JPRM repo
      shell: bash
      run: |
        # initialize repo if it doesn't exist
        ${{ steps.setup-python.outputs.python-path }} \
          -m jprm \
          repo init \
          ${{ steps.inputs.outputs.branch }} || true  # ignore error if already exists

        # add plugin to repo
        if [ "${{ steps.inputs.outputs.action }}" == "add" ]; then
          ${{ steps.setup-python.outputs.python-path }} \
            -m jprm \
            repo add \
            --url ${{ steps.inputs.outputs.gh_pages_url }} \
            --plugin-url ${{ steps.inputs.outputs.plugin_url }} \
            ${{ steps.inputs.outputs.branch }} \
            ${{ steps.inputs.outputs.zipfile_path }}
        elif [ "${{ steps.inputs.outputs.action }}" == "remove" ]; then
          ${{ steps.setup-python.outputs.python-path }} \
            -m jprm \
            repo remove \
            ${{ steps.inputs.outputs.branch }} \
            ${{ steps.inputs.outputs.plugin_name }} \
            ${{ steps.inputs.outputs.release_version }}
        fi

    - name: Publish gh-pages
      uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772  # v1.4
      with:
        github_token: ${{ inputs.github_token }}
        author_email: ${{ inputs.committer_email }}
        author_name: ${{ inputs.committer_name }}
        directory: ${{ steps.inputs.outputs.branch }}
        branch: ${{ steps.inputs.outputs.branch }}
        force: false
        message: "chore: bump ${{ steps.inputs.outputs.source_repository }} to ${{ steps.inputs.outputs.release_tag }}"
        repository: ${{ steps.inputs.outputs.repository }}
