---
name: CI
permissions: {}

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed for release-setup action
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Setup Release
        id: release-setup
        uses: LizardByte/actions/actions/release_setup@200eaeb897a2b065a65cb6f16b41077432007490  # v2026.605.34721
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Update GitHub Release
        if: steps.release-setup.outputs.publish_release == 'true'
        uses: LizardByte/actions/actions/release_create@200eaeb897a2b065a65cb6f16b41077432007490  # v2026.605.34721
        with:
          allowUpdates: false
          artifacts: ''
          body: ${{ steps.release-setup.outputs.release_body }}
          draft: true
          generateReleaseNotes: ${{ steps.release-setup.outputs.release_generate_release_notes }}
          name: ${{ steps.release-setup.outputs.release_tag }}
          prerelease: true
          tag: ${{ steps.release-setup.outputs.release_tag }}
          token: ${{ secrets.GH_BOT_TOKEN }}
