---
name: CI
permissions: {}

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed for release-setup action
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Setup Release
        id: release-setup
        uses: LizardByte/actions/actions/release_setup@d0ae7f82215a479fe2b74f4088c53ee6460513dd  # v2026.728.214955
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Update GitHub Release
        if: steps.release-setup.outputs.publish_release == 'true'
        uses: LizardByte/actions/actions/release_create@d0ae7f82215a479fe2b74f4088c53ee6460513dd  # v2026.728.214955
        with:
          allowUpdates: false
          artifacts: ''
          body: ${{ steps.release-setup.outputs.release_body }}
          draft: true
          generateReleaseNotes: ${{ steps.release-setup.outputs.release_generate_release_notes }}
          name: ${{ steps.release-setup.outputs.release_tag }}
          prerelease: true
          tag: ${{ steps.release-setup.outputs.release_tag }}
          token: ${{ secrets.GH_BOT_TOKEN }}
